name: multitec_app
description: Multitec App - A Flutter application for the community management
  of the multitec student association.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  cloud_firestore: ^6.0.1
  collection: ^1.19.1
  device_preview: ^1.3.1
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.1
  dio_cache_interceptor_hive_store: ^4.0.0
  event_bus: ^2.0.1
  firebase_auth: ^6.1.1
  firebase_core: ^4.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^16.0.0
  google_maps_flutter: ^2.12.2
  google_sign_in: ^6.2.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  multiple_result: ^5.2.0
  path: ^1.9.0
  path_provider: ^2.1.5
  sembast: ^3.7.4
  sembast_web: ^2.3.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  commitlint_cli: ^0.8.1
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  husky: ^0.1.7
  json_serializable: ^6.9.0
  mockito: ^5.4.4
  very_good_analysis: ^8.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/pngs/
