name: multitec_app
description: Multitec App - A Flutter application for the community management
  of the multitec student association.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  collection: ^1.19.1
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.1
  dio_cache_interceptor_hive_store: ^4.0.0
  dio_cache_interceptor_isar_store: ^1.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^16.0.0
  google_maps_flutter: ^2.12.2
  intl: ^0.20.2
  multiple_result: ^5.2.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  commitlint_cli: ^0.8.1
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  husky: ^0.1.7
  mockito: ^5.4.4
  very_good_analysis: ^8.0.0

flutter:
  uses-material-design: true
  generate: true
