import Foundation

/// Auto-generated constants from config/api_constants.json
/// DO NOT EDIT MANUALLY - This file is generated by tools/generate_constants.dart
struct ApiConstants {
    /// Channel name for API key configuration between Flutter and native platforms
    static let apiKeyChannelName = "api_key_config"
    
    /// Method name for setting Google Maps API key
    static let setGoogleMapsApiKeyMethod = "setGoogleMapsApiKey"
}
