// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPnSVjc5MonQR268H4WH_A6zj9DeX-8UA',
    appId: '1:579200226559:web:182459b3370af58d9de8ca',
    messagingSenderId: '579200226559',
    projectId: 'multitec-app-prod',
    authDomain: 'multitec-app-prod.firebaseapp.com',
    storageBucket: 'multitec-app-prod.firebasestorage.app',
    measurementId: 'G-FL16KH9DPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxgw62rZ1rDTfUFpEIzmR135-59QfqU20',
    appId: '1:579200226559:android:269955cb18a355439de8ca',
    messagingSenderId: '579200226559',
    projectId: 'multitec-app-prod',
    storageBucket: 'multitec-app-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhKygGDuFjrJdr7EqgRpqgOdwQF9SxtmE',
    appId: '1:579200226559:ios:9776e2de8fa549a19de8ca',
    messagingSenderId: '579200226559',
    projectId: 'multitec-app-prod',
    storageBucket: 'multitec-app-prod.firebasestorage.app',
    iosBundleId: 'com.multitec.app',
  );
}
