import 'dart:convert';
import 'dart:io';

void main() async {
  // Read the JSON configuration
  final configFile = File('config/api_constants.json');
  if (!await configFile.exists()) {
    print('Error: config/api_constants.json not found');
    exit(1);
  }

  final configContent = await configFile.readAsString();
  final config = jsonDecode(configContent) as Map<String, dynamic>;

  // Generate Dart constants
  await _generateDartConstants(config);

  // Generate Swift constants
  await _generateSwiftConstants(config);

  print('Constants generated successfully!');
}

Future<void> _generateDartConstants(Map<String, dynamic> config) async {
  final dartContent = '''
/// Auto-generated constants from config/api_constants.json
/// DO NOT EDIT MANUALLY - This file is generated by tools/generate_constants.dart
class ApiConstants {
  /// Channel name for API key configuration between Flutter and native platforms
  static const String apiKeyChannelName = '${config['api_key_channel_name']}';

  /// Method name for setting Google Maps API key
  static const String setGoogleMapsApiKeyMethod = '${config['set_google_maps_api_key_method']}';
}
''';

  final dartFile = File('lib/core/constants/api_constants.dart');
  await dartFile.parent.create(recursive: true);
  await dartFile.writeAsString(dartContent);
  print('Generated: lib/core/constants/api_constants.dart');
}

Future<void> _generateSwiftConstants(Map<String, dynamic> config) async {
  final swiftContent = '''
import Foundation

/// Auto-generated constants from config/api_constants.json
/// DO NOT EDIT MANUALLY - This file is generated by tools/generate_constants.dart
struct ApiConstants {
    /// Channel name for API key configuration between Flutter and native platforms
    static let apiKeyChannelName = "${config['api_key_channel_name']}"
    
    /// Method name for setting Google Maps API key
    static let setGoogleMapsApiKeyMethod = "${config['set_google_maps_api_key_method']}"
}
''';

  final swiftFile = File('ios/Runner/ApiConstants.swift');
  await swiftFile.parent.create(recursive: true);
  await swiftFile.writeAsString(swiftContent);
  print('Generated: ios/Runner/ApiConstants.swift');
}
