/// Auto-generated constants from config/api_constants.json
/// DO NOT EDIT MANUALLY - This file is generated by tools/generate_constants.dart
class ApiConstants {
  /// Channel name for API key configuration between Flutter and native platforms
  static const String apiKeyChannelName = 'api_key_config';

  /// Method name for setting Google Maps API key
  static const String setGoogleMapsApiKeyMethod = 'setGoogleMapsApiKey';
}
